### ISSUE TITLE
Undeclared dependency on lxml

### ISSUE THREAD

**Issue by gregneagle** [CLCMacTeam/AutoPkgBESEngine#2]
See Slack discussion here: https://macadmins.slack.com/archives/autopkg/p1454698514002031

Looks like AutoPkgBESEngine depends on lxml, which is not part of the Python standard library. At the very least you should document that; better would be to also document how one might _install_ lxml; still better would be to see if AutoPkgBESEngine could use Python's standard xml.etree library instead, eliminating the external dependency.

**Comment by gregneagle** [comment]
At least one more undeclared dependency:  https://github.com/CLCMacTeam/besapi
There may be more...

**Comment by hansen-m** [comment]
Thanks! Updated here - https://github.com/CLCMacTeam/AutoPkgBESEngine/commit/2729739db766985a75f234f0ee4d090c280a5e94

Regarding to the Slack discussion, the BESRelevanceProvider is useful and installable outside of AutoPkgBESEngine so I'll work on separating that out as a SharedProcessor.
